### ISSUE TITLE
fail to start on Fedora33/aarch64/Python3.9.1  "AttributeError: type object 'method' has no attribute 'start'"

### ISSUE THREAD

**Issue by hptf** [20c/vaping#106]
Any clue what going wrong with a fresh start ?
vaping start --home=examples/standalone_dns/ --debug

`
 vaping start --home=examples/standalone_dns/ --debug
pluginmgr hook.compile(vaping.plugins) __init__.py:25
PidFile <pid.posix.PidFile object at 0xffff7fa10700> entering setup base.py:89
PidFile <pid.posix.PidFile object at 0xffff7fa10700> create pidfile: /home/freebox/git/vaping/examples/standalone_dns/vaping.pid base.py:194
PidFile <pid.posix.PidFile object at 0xffff7fa10700> check pidfile: /home/freebox/git/vaping/examples/standalone_dns/vaping.pid base.py:181
2021-02-23 14:55:00,626 - vaping.plugins.fping - DEBUG: popen fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 208.67.222.222
vaping.plugins.fping popen fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 208.67.222.222 __init__.py:112
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0xffff81035940>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/logging/__init__.py", line 251, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()
  File "/usr/lib64/python3.9/logging/__init__.py", line 890, in _at_fork_reinit
    self.lock._at_fork_reinit()
  File "/usr/lib64/python3.9/threading.py", line 126, in _at_fork_reinit
    self._block._at_fork_reinit()
AttributeError: 'LockType' object has no attribute '_at_fork_reinit'
root 8.8.8.8        : - - - - - - - - - -
 fping.py:85
root 4.2.2.1        : - - - - - - - - - -
 fping.py:85
root 208.67.222.222 : - - - - - - - - - -
 fping.py:85
2021-02-23 14:55:00,958 - vaping.plugins.fping - DEBUG: queue emission to vodka (0)
vaping.plugins.fping queue emission to vodka (0) __init__.py:206
2021-02-23 14:55:03,629 - vaping.plugins.fping - DEBUG: emit to vodka
vaping.plugins.fping emit to vodka __init__.py:203
2021-02-23 14:55:03,788 - vodka - DEBUG: making sure configuration is sane ...
vodka making sure configuration is sane ... log.py:39
2021-02-23 14:55:03,807 - vodka - DEBUG: instantiating data types
vodka instantiating data types log.py:39
2021-02-23 14:55:03,808 - vodka - DEBUG: instantiating plugins
vodka instantiating plugins log.py:39
2021-02-23 14:55:03,817 - vodka - DEBUG: instantiating applications
vodka instantiating applications log.py:39
2021-02-23 14:55:03,818 - vodka - DEBUG: starting plugins
vodka starting plugins log.py:39
2021-02-23 14:55:03,828 - vodka - DEBUG: starting http ..
vodka starting http .. log.py:39
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 251, in _run
    self.emit_all()
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 227, in emit_all
    self.send_emission()
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 220, in send_emission
    emit()
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 204, in emit
    emitter.emit(msg)
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/vodka.py", line 99, in emit
    self.start()
  File "/home/freebox/.local/lib/python3.9/site-packages/vaping/plugins/vodka.py", line 87, in start
    vodka.run(vodka_config, self.vaping.config)
  File "/home/freebox/.local/lib/python3.9/site-packages/vodka/__init__.py", line 148, in run
    start(**init(config, rawConfig))
  File "/home/freebox/.local/lib/python3.9/site-packages/vodka/__init__.py", line 116, in start
    t.start()
  File "/usr/lib64/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
  File "/home/freebox/.local/lib/python3.9/site-packages/gevent/thread.py", line 81, in start_new_thread
    greenlet = Greenlet.spawn(function, *args)
  File "src/gevent/greenlet.py", line 663, in gevent._greenlet.Greenlet.spawn
AttributeError: type object 'method' has no attribute 'start'
2021-02-23T14:55:03Z <FPing "latency" at 0xffff7fb9ebf0: _run> failed with AttributeError

2021-02-23 14:55:03,846 - vaping.daemon - ERROR: This operation would block forever
        Hub: <Hub '' at 0xffff7fd4e460 epoll default pending=0 ref=0 fileno=3 thread_ident=0xffff81afdd20>
        Handles:
[]
vaping.daemon This operation would block forever
        Hub: <Hub '' at 0xffff7fd4e460 epoll default pending=0 ref=0 fileno=3 thread_ident=0xffff81afdd20>
        Handles:
[] daemon.py:182
PidFile <pid.posix.PidFile object at 0xffff7fa10700> closing pidfile: /home/freebox/git/vaping/examples/standalone_dns/vaping.pid base.py:220
2021-02-23 14:55:03,848 - vaping.daemon - DEBUG: stopping vodka
vaping.daemon stopping vodka daemon.py:222
2021-02-23 14:55:03,849 - vaping.daemon - DEBUG: stopping latency
vaping.daemon stopping latency daemon.py:222
PidFile <pid.posix.PidFile object at 0xffff7fa10700> closing pidfile: /home/freebox/git/vaping/examples/standalone_dns/vaping.pid base.py:220
`

**Comment by vegu** [comment]
Python3.9 is not supported yet (see #102 and #103) - ill add some extra symptomatic information to #103.

The user in #102 was able to downgrade to py3.8, is this an option for you? (36 or 37 should work as well)
