### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by aspiers** [20c/vaping#12]
`vaping` frequently crashes on me.  My instinct is that this happens when one of the hosts it is trying to fping becomes unreachable, but I could be wrong.  It looks like the problem is actually in [`vodka`](https://github.com/20c/vodka/) so I'm happy to resubmit the issue there if you prefer.  Either way, hopefully this debug is enough to figure it out:

```
vaping.plugins.fping sending __init__.py:133
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 134, in _run
    self._emit.emit(msg)
  File "/usr/lib/python2.7/site-packages/vaping/plugins/vodka.py", line 56, in emit
    vodka.data.handle(data.get("type"), data, data_id=data.get("source"), caller=self)
  File "/usr/lib/python2.7/site-packages/vodka/data/__init__.py", line 34, in handle
    data = handler(data, caller=caller)
  File "/usr/lib/python2.7/site-packages/vodka/data/handlers.py", line 93, in __call__
    for d in data["data"]])
TypeError: 'NoneType' object has no attribute '__getitem__'
Wed Apr 19 12:56:16 2017 <FPing at 0x7f1f27667d70> failed with TypeError

vaping.daemon stopping vodka daemon.py:157
vaping.daemon stopping latency daemon.py:157
Traceback (most recent call last):
  File "/usr/bin/vaping", line 11, in <module>
    load_entry_point('vaping==0.3.0', 'console_scripts', 'vaping')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vaping/cli.py", line 57, in start
    daemon.run()
  File "/usr/lib/python2.7/site-packages/vaping/daemon.py", line 147, in run
    return self._main()
  File "/usr/lib/python2.7/site-packages/vaping/daemon.py", line 118, in _main
    vaping.io.joinall(self.joins)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 649, in joinall
    return wait(greenlets, timeout=timeout, count=count)
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 1038, in wait
    return list(iwait(objects, timeout, count))
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 985, in iwait
    item = waiter.get()
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 939, in get
    Waiter.get(self)
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f1f27667370 epoll default pending=0 ref=0 fileno=3>)
```

**Comment by vegu** [comment]
Hi,

This is indeed an issue on the vodka end, i've made a corresponding ticket there, thanks for the report.

https://github.com/20c/vodka/issues/8

**Comment by vegu** [comment]
I released vodka 2.2.2 just now which contains a fix for the initial issue, although now that i looked at it some more its curious that the gevent loop would exit with a block forever error, so i am reopening, please let us know if the fix in vodka 2.2.2 fixed your crashing issue.

**Comment by aspiers** [comment]
Awesome, thanks!  I've just upgraded to 2.2.2 and restarted vaping, so we'll see how long it lasts.  I have enough packet loss that if it runs for more than a day then I'm pretty confident we can close this.

**Comment by aspiers** [comment]
It's still running, so I think this is almost certainly fixed now :-)
