### ISSUE TITLE
OSError: config file not found in examples/standalone_dns

### ISSUE THREAD

**Issue by cas--** [20c/vaping#123]
I am trying to follow the [quickstart guide]https://vaping.readthedocs.io/en/stable/quickstart/) but getting the following error:

```
$ vaping start --home examples/standalone_dns 
Traceback (most recent call last):
  File "/home/casadmin/.pyenv/versions/3.9.6/bin/vaping", line 8, in <module>
    sys.exit(cli())
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/vaping/cli.py", line 72, in start
    update_context(ctx, kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/vaping/cli.py", line 21, in update_context
    ctx.update_options(kwargs)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/munge/click.py", line 119, in update_options
    self.config = self.config_class(read=self.home)
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/munge/config.py", line 54, in __init__
    self.read(kwargs["read"])
  File "/home/casadmin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/munge/config.py", line 133, in read
    raise OSError(f"config file not found in {conf_path}")
OSError: config file not found in examples/standalone_dns
```

```
$ vaping --version
vaping, version 1.4.1
$ python --version
Python 3.9.6
$ pip list
Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.3
click              8.0.1
confu              1.8.0
docutils           0.17.1
Flask              1.1.2
graphsrv           2.0.0
idna               3.2
itsdangerous       2.0.1
Jinja2             2.11.3
lockfile           0.12.2
MarkupSafe         2.0.1
munge              1.2.0
pid                3.0.4
pip                21.1.3
pluginmgr          1.0.1
python-daemon      2.3.0
requests           2.26.0
setuptools         56.0.0
tmpl               1.0.0
urllib3            1.26.6
vaping             1.4.1
vodka              3.1.0
Werkzeug           2.0.1
```

**Comment by cas--** [comment]
It seems to be an issue with `munge` 1.2 since install old version works:

     pip install munge==1.1

**Comment by bile0026** [comment]
> ```
>  pip install munge==1.1
> ```

Having this same issue, but switching to munge==1.1 not solving the issue. I am on Python 3.6.8 though. Maybe I need to be on 3.9.6?

**Comment by bile0026** [comment]
> > ```
> >  pip install munge==1.1
> > ```
> 
> Having this same issue, but switching to munge==1.1 not solving the issue. I am on Python 3.6.8 though. Maybe I need to be on 3.9.6?

Upgrading to Python 3.9.6 with munge 1.1, did not resolve the issue for me. Still can't find config file, which exists if I ls the directory. Doesn't seem to be permissions either as this is in my home dir.

**Comment by grizz** [comment]
Hrm, looking into this now, thanks!

**Comment by bile0026** [comment]
Some more info, I can run it okay now in a venv on Python 3.9.6 and munge 1.2.0 when I run `vaping start --home=examples/distributed_dns/vaping/ --debug`, but trying to run through gunicorn or uwsgi gives the OSException, can't find config file.

**Comment by grizz** [comment]
@cas-- @bile0026 Does `pip install pyyaml` fix it?

**Comment by bile0026** [comment]
> @cas-- @bile0026 Does `pip install pyyaml` fix it?

Nope, already installed 
```
(vaping) [zbiles@vlpingp01 vaping]$ pip install PyYAML
Requirement already satisfied: PyYAML in ./lib/python3.9/site-packages (5.4.1)
```

**Comment by grizz** [comment]
@bile0026 hrm, did for me. Could you dump your full environment please? (Like cas-- did in the first comment)

**Comment by bile0026** [comment]
For sure, here you go. 

```
$ gunicorn -b 127.0.0.1:7021 vodka.runners.wsgi:application
[2021-07-20 18:41:03 +0000] [11579] [INFO] Starting gunicorn 20.1.0
[2021-07-20 18:41:03 +0000] [11579] [INFO] Listening at: http://127.0.0.1:7021 (11579)
[2021-07-20 18:41:03 +0000] [11579] [INFO] Using worker: sync
[2021-07-20 18:41:03 +0000] [11580] [INFO] Booting worker with pid: 11580
[2021-07-20 18:41:03 +0000] [11580] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/runners/wsgi.py", line 11, in <module>
    config.read(config_dir=os.environ.get("VODKA_HOME", "."))
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/config/__init__.py", line 420, in read
    return super().read(config_dir=config_dir, clear=clear)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/munge/config.py", line 128, in read
    raise OSError(f"config dir not found at {conf_path}")
OSError: config dir not found at examples/standalone_dns/vodka
[2021-07-20 18:41:03 +0000] [11580] [INFO] Worker exiting (pid: 11580)
[2021-07-20 18:41:03 +0000] [11579] [INFO] Shutting down: Master
[2021-07-20 18:41:03 +0000] [11579] [INFO] Reason: Worker failed to boot.
```

```
$ vaping --version
vaping, version 1.4.1
$ python --version
Python 3.9.2
$ pip list
Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.3
click              8.0.1
confu              1.8.0
docutils           0.17.1
Flask              1.1.4
graphsrv           2.0.0
gunicorn           20.1.0
idna               3.2
itsdangerous       1.1.0
Jinja2             2.11.3
lockfile           0.12.2
MarkupSafe         2.0.1
munge              1.2.0
pid                3.0.4
pip                21.1.3
pluginmgr          1.0.1
python-daemon      2.3.0
PyYAML             5.4.1
pyyml              0.0.2
pyzmq              22.1.0
requests           2.26.0
setuptools         50.3.2
tmpl               1.0.0
urllib3            1.26.6
vaping             1.4.1
vodka              3.1.0
Werkzeug           1.0.1
wheel              0.36.2
zmq                0.0.0
```

**Comment by grizz** [comment]
@bile0026 The problem is it's looking for a config file in `examples/standalone_dns/vodka` which isn't there -- could you double check your config?

**Comment by bile0026** [comment]
> @bile0026 The problem is it's looking for a config file in `examples/standalone_dns/vodka` which isn't there -- could you double check your config?

Well I feel dumb, thanks for that. I was trying to combine the "standalone" with "distributed" example and didn't realize the paths weren't the same 🙄 Looks like there's another error, but I'll spend some time on that and open a new issue if required. Thanks for the quick response!

**Comment by grizz** [comment]
No problem, let us know if you have any more issues!

**Comment by athompson-merlin** [comment]
Err... I'm getting the same problem with munge==1.2.1 on a fresh install today, on Alma Linux 8 (an EL8 rebuild) with system-python 3.6.8.  

The `pip install` commands from the quickstart appear to have installed munge v1.2.1 which, according to strace(8), never _attempts_ to open the config file.  I don't know why 1.2.1 got installed instead of 1.2.0 as specified in the deps file.

Munge v1.2.0 also works fine, which is bizarre... I'm looking at the commits between munge 1.2.0 and 1.2.1, and there's nothing in there that should make any difference, unless the problem is in the downstream module "click" v8?
