### ISSUE TITLE
Is HTTPS supported?

### ISSUE THREAD

**Issue by bile0026** [20c/vaping#125]
I have enabled HTTPS using Nginx Reverse proxy running a standalone instance but receiving some "Mixed content" errors. I'm not seeing anything in the config.yml or elsewhere to serve scripts over https. Is this not a supported feature?

```
Mixed Content: The page at 'https://<server_name>/' was loaded over HTTPS, but requested an insecure script 'http://<server_name>/graph/?targets=all&id=auto-1&fit=yes&type=multitarget&config=multitarget&source=latency.First%20Group'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by grizz** [comment]
Yes, it's supported. That's how https://vaping.20c.com/ is setup.

**Comment by bile0026** [comment]
> Yes, it's supported. That's how https://vaping.20c.com/ is setup.

Special configuration required? Any Tips?

Guts Nginx config:
```
upstream vaping {
    	server 127.0.0.1:7021;
    }

    server {
    if ($host = vaping.fqdn) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  vaping.fqdn;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
	return 301 https://$host$request_uri;

        location / {
#		proxy_pass http://vaping;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }


}

# Settings for a TLS enabled server.
#
    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  vaping.fqdn;
        root         /usr/share/nginx/html;

        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers PROFILE=SYSTEM;
        ssl_prefer_server_ciphers on;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
	  proxy_pass_request_headers on;
	  proxy_set_header Host $host;
	  proxy_set_header X-Real-IP $remote_addr;
	  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	  proxy_set_header Accept-Encoding "";

	  auth_basic "Restricted";
  	  auth_basic_user_file .htpasswd;

	  proxy_pass http://vaping;

	  #proxy_redirect default;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }

    ssl_certificate /etc/letsencrypt/live/vaping.fqdn/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/vaping.fqdn/privkey.pem; # managed by Certbot
}
```

**Comment by grizz** [comment]
We use uwsgi instead of http, I'll push a config example in a few.

**Comment by grizz** [comment]
@bile0026 https://github.com/20c/vaping/tree/master/docs/config/nginx-uwsgi

I have no reason to think http instead of uwsgi, @vegu can you think of anything?

We can test and get more examples up later.

**Comment by bile0026** [comment]
> @bile0026 https://github.com/20c/vaping/tree/master/docs/config/nginx-uwsgi
> 
> I have no reason to think http instead of uwsgi, @vegu can you think of anything?
> 
> We can test and get more examples up later.

I think I have uwsgi running now but it's still trying to serve that .js file via HTTP. Assuming this is due to `--socket=0.0.0.0:7026"??

`uwsgi -H $VIRTUAL_ENV --socket=0.0.0.0:7026 -w vodka.runners.wsgi:application --enable-threads`

Tried something like this, but ran into more errors. 

```
$ uwsgi -H $VIRTUAL_ENV --https=0.0.0.0:7026,/etc/letsencrypt/live/vaping.fqdn/fullchain.pem,/etc/letsencrypt/live/vaping.sisulink.app/privkey.pem -w vodka.runners.wsgi:application --enable-threads
[uwsgi-ssl] unable to assign certificate /etc/letsencrypt/live/vaping.fqdn/fullchain.pem for context "http-0.0.0.0:7026"
```

Not really sure what to try next as the uwsgi documentation isn't particularly clear either. TBH this is my first time using uwsgi so I'm trying to learn this all on the fly.

**Comment by grizz** [comment]
@bile0026 It shouldn't have anything to do with that, where are you seeing that error exactly? Is that anywhere public? (or can email me if you don't want to post here).

**Comment by bile0026** [comment]
After some modification of nginx I am using this and it seemed to work partially, but I was getting blank graphs.
`uwsgi -H $VIRTUAL_ENV --socket :7026 -w vodka.runners.wsgi:application --enable-threads`

Changed up the config file to be based on the `examples/standalone_dns/config.yml` (just put my own IP's instead of the dns IP's, and changed plugins['http'].server to uwsgi. I didn't change anything else.) Now I'm getting an error that it can't find the fping plugin. So I'm not sure if I'm going backwards here or actually making progress? 

```
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Jul 20 22:07:30 2021] ***
compiled with version: 8.5.0 20210514 (Red Hat 8.5.0-2) on 21 July 2021 01:16:53
os: Linux-4.18.0-315.el8.x86_64 #1 SMP Mon Jun 28 19:09:44 UTC 2021
nodename: vlpingp01
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/zbiles/customer_jobs/northern_wireless/vaping
detected binary path: /home/zbiles/customer_jobs/northern_wireless/vaping/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3099
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :7026 fd 5
Python version: 3.9.2 (default, May  6 2021, 16:40:51)  [GCC 8.4.1 20210423 (Red Hat 8.4.1-2)]
PEP 405 virtualenv detected: /home/zbiles/customer_jobs/northern_wireless/vaping
Set PythonHome to /home/zbiles/customer_jobs/northern_wireless/vaping
Python main interpreter initialized at 0x1ad3fe0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
2021-07-20 22:07:31,274 - vodka - DEBUG: making sure configuration is sane ...
2021-07-20 22:07:31,275 - vodka - WARNING: [config unknown] 'probes is not a known configuration variable and has been ignored'
Traceback (most recent call last):
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/runners/wsgi.py", line 13, in <module>
    vodka.run(config, config)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/__init__.py", line 144, in run
    start(**init(config, rawConfig))
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/__init__.py", line 40, in init
    num_crit, num_warn = vodka.config.InstanceHandler.validate(cfg)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/config/__init__.py", line 256, in validate
    _num_crit, _num_warn = cls.check(cfg, key, path)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/config/__init__.py", line 157, in check
    handler = attr.handler(k, value[k])
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vodka/config/__init__.py", line 341, in <lambda>
    handler=lambda k, v: vodka.plugin.get_plugin_class(v.get("type")),
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/pluginmgr/__init__.py", line 202, in get_plugin_class
    raise ValueError(f"unknown plugin '{typ}'")
ValueError: unknown plugin 'fping'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 35032, cores: 1)
```

pip freeze:
```
backports.entry-points-selectable==1.1.0
certifi==2021.5.30
charset-normalizer==2.0.3
click==8.0.1
confu==1.8.0
distlib==0.3.2
docutils==0.17.1
filelock==3.0.12
Flask==1.1.2
fping==0.0.1a2
graphsrv==2.0.0
gunicorn==20.1.0
idna==3.2
itsdangerous==1.1.0
Jinja2==2.11.3
lockfile==0.12.2
MarkupSafe==2.0.1
munge==1.2.0
netaddr==0.8.0
pid==3.0.4
platformdirs==2.0.2
pluginmgr==1.0.1
python-daemon==2.3.0
PyYAML==5.4.1
pyyml==0.0.2
pyzmq==19.0.2
requests==2.26.0
six==1.16.0
tmpl==1.0.0
tomlkit==0.7.2
urllib3==1.26.6
uWSGI==2.0.19.1
vaping==1.4.1
virtualenv==20.6.0
vodka==3.1.0
Werkzeug==1.0.1
whisper==1.1.8
zmq==0.0.0
```


I do have it public, but not sure it will do much good until I can get the webserver to actually start.

**Comment by vegu** [comment]
To run the webservice through uwsgi (or gunicorn) it requires a distributed setup. 

This can still be setup on the same host, but the vaping and webservice configs needs to be separated as shown in the distributed_dns example ([here](https://vaping.readthedocs.io/en/stable/quickstart/)) - and you will run two processes

1. uwsgi for the vodka web service
2. vaping to feed data to the webservice through zmq.

Passing the standalone config to uswgi wont work since vodka will be the controlling framework, and doesn't know how to run the vaping process (which i suppose might manifest in the unknown plugin error you are seeing above, both vodka and vaping using the same plugin manager)

**Comment by bile0026** [comment]
> To run the webservice through uwsgi (or gunicorn) it requires a distributed setup. 
> 
> 
> 
> This can still be setup on the same host, but the vaping and webservice configs needs to be separated as shown in the distributed_dns example ([here](https://vaping.readthedocs.io/en/stable/quickstart/)) - and you will run two processes
> 
> 
> 
> 1. uwsgi for the vodka web service
> 
> 2. vaping to feed data to the webservice through zmq.
> 
> 
> 
> Passing the standalone config to uswgi wont work since vodka will be the controlling framework, and doesn't know how to run the vaping process (which i suppose might manifest in the unknown plugin error you are seeing above, both vodka and vaping using the same plugin manager)

That makes sense, I will give this a try as soon as I have some time to get back on this project.

**Comment by bile0026** [comment]
Finally have time to get back to this. Trying to run vaping and getting a plugin error even though I have pyzmq installed. Is there some specific setup needed to make this work? This is using the example configs.


```
(vaping) [zbiles@vlpingp01 vaping]$ pip list
Package                           Version
--------------------------------- ---------
backports.entry-points-selectable 1.1.0
certifi                           2021.5.30
charset-normalizer                2.0.3
click                             8.0.1
confu                             1.8.0
distlib                           0.3.2
docutils                          0.17.1
filelock                          3.0.12
Flask                             1.1.2
fping                             0.0.1a2
gevent                            21.1.2
graphsrv                          2.0.0
greenlet                          1.1.0
gunicorn                          20.1.0
idna                              3.2
itsdangerous                      1.1.0
Jinja2                            2.11.3
lockfile                          0.12.2
MarkupSafe                        2.0.1
munge                             1.2.0
netaddr                           0.8.0
pid                               3.0.4
pip                               21.2.1
platformdirs                      2.0.2
pluginmgr                         1.0.1
python-daemon                     2.3.0
PyYAML                            5.4.1
pyyml                             0.0.2
pyzmq                             19.0.2
requests                          2.26.0
setuptools                        57.4.0
six                               1.16.0
tmpl                              1.0.0
tomlkit                           0.7.2
urllib3                           1.26.6
uWSGI                             2.0.19.1
vaping                            1.4.1
virtualenv                        20.6.0
vodka                             3.1.0
Werkzeug                          1.0.1
wheel                             0.36.2
whisper                           1.1.8
zmq                               0.0.0
zope.event                        4.5.0
zope.interface                    5.4.0
```

```
(vaping) [zbiles@vlpingp01 vaping]$ vaping start --home=examples/distributed_dns/vaping/ --debug
pluginmgr hook.compile(vaping.plugins) __init__.py:23
pluginmgr hook.namespace vaping.plugins __init__.py:42
pluginmgr hook.find(zmq.libzmq, ['/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/zmq']) loader=False __init__.py:43
pluginmgr match None __init__.py:52
pluginmgr hook.namespace vaping.plugins __init__.py:42
pluginmgr hook.find(cPickle, None) loader=False __init__.py:43
pluginmgr match None __init__.py:52
pluginmgr hook.namespace vaping.plugins __init__.py:42
pluginmgr hook.find(simplejson, None) loader=False __init__.py:43
pluginmgr match None __init__.py:52
pluginmgr hook.namespace vaping.plugins __init__.py:42
pluginmgr hook.find(jsonlib2, None) loader=False __init__.py:43
pluginmgr match None __init__.py:52
pluginmgr hook.namespace vaping.plugins __init__.py:42
pluginmgr hook.find(cPickle, None) loader=False __init__.py:43
pluginmgr match None __init__.py:52
Traceback (most recent call last):
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/bin/vaping", line 8, in <module>
    sys.exit(cli())
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vaping/cli.py", line 74, in start
    daemon = mk_daemon(ctx)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vaping/cli.py", line 47, in mk_daemon
    return vaping.daemon.Vaping(config_dir=ctx.home)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vaping/daemon.py", line 49, in __init__
    self.validate_config_data(self.config.data)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vaping/daemon.py", line 122, in validate_config_data
    VapingSchema().validate(config_data)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 617, in validate
    errors.error(error)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 455, in error
    raise error
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 613, in validate
    config[key] = attribute.validate(
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 442, in validate
    errors.error(error)
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 455, in error
    raise error
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 434, in validate
    self.item.validate(
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/vaping/config/schema.py", line 62, in validate
    return self.schema(config).validate(
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 623, in validate
    errors.error(ValidationError(attribute, path + [name], None, "missing"))
  File "/home/zbiles/customer_jobs/northern_wireless/vaping/lib64/python3.9/site-packages/confu/schema/core.py", line 455, in error
    raise error
confu.exceptions.ValidationError: ['plugins', 'zmq_vodka', 'connect']: missing
```

**Comment by vegu** [comment]
@bile0026 It's a configuration validation error, its looking for the `connect` attribute in `plugins.zmq_vodka`

That looks like a bug either with our examples or the configuration validation schema.

Try copying the `bind` attribute to `connect` and see if that fixes your issue

**Comment by bile0026** [comment]
> @bile0026 It's a configuration validation error, its looking for the `connect` attribute in `plugins.zmq_vodka`
> 
> EDIT: That looks like a bug with our config validation for the zeromq plugin. Its looking for `connect` even though `bind` is already set. Opened issue at #126.
> 
> I will try to push a fix out for this soon - for now you could try simply adding the following to the plugin config (haven't tested):
> 
> ```yaml
> connect: ''
> ```

Looks like that won't work, so I'll wait for the fix. 

```
confu.exceptions.ValidationError: ['plugins', 'zmq_vodka', 'connect']: cannot be blank
```

And if I try and specifiy something in the connect field (this looks to be expected behavior):
```
ValueError: bind and connect are mutually exclusive
```

**Comment by vegu** [comment]
@bile0026 fix for #126 has been pushed out in release 1.4.3

**Comment by bile0026** [comment]
> @bile0026 fix for #126 has been pushed out in release 1.4.3

I still seem to be getting the same error as before. 

```
confu.exceptions.ValidationError: ['plugins', 'zmq_vodka', 'connect']: missing
```

`examples/distributed_dns/vaping/config.yml`
```
probes:
  - name: latency
    type: std_fping
    output:
      - zmq_vodka

    groups:
      - name: public_dns
        hosts:
          - host: 8.8.8.8
            name: Google
            color: red
          - host: 4.2.2.1
            name: Level(3)
            color: blue
          - host: 208.67.222.222
            name: OpenDNS
            color: orange

plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s

  - name: zmq_vodka
    type: zeromq
    bind: tcp://127.0.0.1:6021



logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    #file:
    #  class: logging.FileHandler
    #  level: DEBUG
    #  formatter: simple
    #  filename: /home/dev/sandbox/vaping/vaping.log

  loggers:
    vaping:
      level: DEBUG
      handlers:
        - console
        #- file
```

**Comment by vegu** [comment]
@bile0026 am unable to reproduce with 1.4.3 installed and the config you pasted above

can you confirm that pip freeze comes up with vaping installed as 1.4.3?

**Comment by bile0026** [comment]
> @bile0026 am unable to reproduce with 1.4.3 installed and the config you pasted above
> 
> can you confirm that `pip freeze` comes up with vaping installed as 1.4.3?

I forgot to upgrade vaping with pip, my bad. Looks like it will launch now without the error. Now I can get back to figuring out UWSGI, thanks!

**Comment by bile0026** [comment]
Got this working now, thank you for the help!
