### ISSUE TITLE
Run issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by heathdbrown** [20c/vaping#22]
When following http://vaping.readthedocs.io/en/latest/quickstart/#example-standalone-latency I am encountering an error on start-up any help would be appreciated.

OS: Ubuntu 16.04
Version: 0.3.0

Command:
```
~/vaping$ sudo vaping start --home=examples/standalone_dns/ --debug
```

Error:
```
pluginmgr hook.compile(vaping.plugins) __init__.py:24
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.3.0', 'console_scripts', 'vaping')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/usr/local/lib/python2.7/dist-packages/vaping/daemon.py", line 59, in __init__
    plugin.instantiate(self.config['plugins'], self.plugin_context)
AttributeError: 'PluginManager' object has no attribute 'instantiate'
```

**Comment by vegu** [comment]
Can you run `pip freeze` and paste the result please. Mostly interested in what version of **pluginmgr** you have installed.

**Comment by heathdbrown** [comment]
Here is the pip freeze, as requested.

Looks like I am running 0.5.0 on pluginmgr.

```
pluginmgr==0.5.0
```

```
pip freeze
beautifulsoup4==4.4.1
boto==2.38.0
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
cryptography==1.2.3
docutils==0.14
duplicity==0.7.6
enum34==1.1.2
Flask==0.12.2
future==0.16.0
gevent==1.2.2
graphsrv==1.1.3
greenlet==0.4.12
html5lib==0.999
idna==2.6
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.9.6
lockfile==0.12.2
lxml==3.5.0
MarkupSafe==1.0
munge==0.4.0
ndg-httpsclient==0.4.0
pid==2.0.1
pluginmgr==0.5.0
pyasn1==0.1.9
pygobject==3.20.0
pyOpenSSL==0.15.1
python-cloudfiles==1.7.10
python-daemon==2.1.1
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
six==1.10.0
twentyc.tmpl==0.2.0
urllib3==1.22
vaping==0.3.0
vodka==2.2.2
Werkzeug==0.12.2
whichcraft==0.4.0
```

**Comment by vegu** [comment]
Can you try manually installing pluginmgr 0.4.0 and see if that fixes the issue, 0.5.0 was released only days ago and i suspect there might be some compatibility issue with vaping.

`pip install pluginmgr==0.4.0`

**Comment by heathdbrown** [comment]
Yeah `pluginmgr 0.4.0` works like a charm.

**Comment by heathdbrown** [comment]
Do you need any debugs to help find the issue in 0.5.0?

**Comment by vegu** [comment]
The traceback above should suffice thank you, and thanks for the bug report. I made a specific ticket to address this issue in #23 - closing this one.
