### ISSUE TITLE
Make vaping work with pluginmgr 0.5.0

### ISSUE THREAD

**Issue by vegu** [20c/vaping#23]
Related to #22 

Alternatively: pin version 0.4.0 in pip requirements

**Comment by vegu** [comment]
pluginmgr hook.compile(vaping.plugins) __init__.py:24
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.3.0', 'console_scripts', 'vaping')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/usr/local/lib/python2.7/dist-packages/vaping/daemon.py", line 59, in __init__
    plugin.instantiate(self.config['plugins'], self.plugin_context)
AttributeError: 'PluginManager' object has no attribute 'instantiate'

**Comment by vegu** [comment]
pinned to pluginmgr 0.4.0 for now
