### ISSUE TITLE
Vaping install issue on Raspberrypi

### ISSUE THREAD

**Issue by heathdbrown** [20c/vaping#24]
Apologies on multiple reports.

This looks like a specific problem with Raspberrypi + pip as vaping installs fine on Ubuntu 16.04.

But, any help on getting pointed in the right direction would be appreciated.

OS: Raspbian GNU/Linux 8 (jessie)
Pip version: 1.5.6

Error:

```
------------------------------------------------------------
/usr/bin/pip run on Sat Sep  9 19:30:55 2017
Downloading/unpacking vaping
  Getting page https://pypi.python.org/simple/vaping/
  URLs to search for versions for vaping:
  * https://pypi.python.org/simple/vaping/
  Analyzing links from page https://pypi.python.org/simple/vaping/
    Found link https://pypi.python.org/packages/14/58/5d404eb95269eb8a395371541804aaa0d4308be57ab388a1ab9165967f55/vaping-0.2.0.tar.gz#md5=82bb7c8be81caf5fe9c121350c928ce6 (from https://pypi.python.org/simple/vaping/), version: 0.2.0
    Found link https://pypi.python.org/packages/90/bd/6b4779ec676d91962c6205c0cfe53821659cf0d5702895e13eee5ac1e1e1/vaping-0.3.0.tar.gz#md5=6de58dbe620f707cc2089e3d3eb8022d (from https://pypi.python.org/simple/vaping/), version: 0.3.0
  Using version 0.3.0 (newest of versions: 0.3.0, 0.2.0)
  Downloading vaping-0.3.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/90/bd/6b4779ec676d91962c6205c0cfe53821659cf0d5702895e13eee5ac1e1e1/vaping-0.3.0.tar.gz#md5=6de58dbe620f707cc2089e3d3eb8022d (from https://pypi.python.org/simple/vaping/)
  Running setup.py (path:/tmp/pip-build-cpbUGX/vaping/setup.py) egg_info for package vaping
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    error in vaping setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'

  warnings.warn(msg)

error in vaping setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-cpbUGX/vaping
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-cpbUGX/vaping
```

**Comment by heathdbrown** [comment]
Ah...I did not read in the previous issues deep enough.

Trying the solution here: https://github.com/20c/vaping/issues/21

**Comment by heathdbrown** [comment]
Interesting in this case I receiving the following when attempting the steps in #21, however I receive the message that it will not be uninstalling as pip is owned by OS.

```
root@homepib:~# pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
root@homepib:~# pip install pip -U
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
root@homepib:~# pip install setuptools -U
Downloading/unpacking setuptools from https://pypi.python.org/packages/1b/95/e6f28144fdb6c06186c1f0e70cea02791e6ec787682bdfc437ce69b8186c/setuptools-36.4.0-py2.py3-none-any.whl#md5=cd2f7498abadf0ef7aff9f9297cae33d
  Downloading setuptools-36.4.0-py2.py3-none-any.whl (478kB): 478kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 5.5.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed setuptools
Cleaning up...
```

**Comment by vegu** [comment]
If possible you should make use of virtualenv (https://pypi.python.org/pypi/virtualenv), it allows you to create self contained python enivornments. Once the environment is activated pip install will install into that environment, leaving the main python installation alone. Also makes it way easier to maintain different python applications on the same box :)

**Comment by heathdbrown** [comment]
Indeed, that was my next troubleshooting step and if anything like previous experiences dictate I should always just start with virtualenv...I thought it would be **easier** just to do a quick install. 

Funny I removed `python-pip` and attempted to re-install pip via `get-pip.py` then found it didn't uninstall pip, then reinstalled `python-pip` and now `pip install vaping` is installed.

New error, but I think this is because of an issue with the installation of vaping.

```
pi@homepib:~/vaping $ vaping start --home=examples/standalone_dns/ --debug
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'whichcraft==0.4.0' distribution was not found and is required by vaping
```

**Error from pip.log from vaping install**
```
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLIBEV_
EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.linux-armv6l-2.7/libev -I/tmp/pip-build-k67j2C/gevent/deps/libev -I/usr/include/python2.7 -c src/gevent/
libev/gevent.corecext.c -o build/temp.linux-armv6l-2.7/src/gevent/libev/gevent.corecext.o
    src/gevent/libev/gevent.corecext.c:5:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-k67j2C/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KDL3DZ-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'cffi_modules'
```

**Comment by heathdbrown** [comment]
Installing `apt-get install python-dev` fixed the compile issues.

Re-installed vaping to fix the previously broken dependencies.

Everything now works.
