### ISSUE TITLE
Ubuntu - Running fail, how to deal with Vaping?

### ISSUE THREAD

**Issue by jorel83** [20c/vaping#45]
Hi all, 

Was very eager to see the alternative to Smokeping, so installed it on a virtual ubuntu 16.04 server, installation seemed way to easy and of course it was. Installed using pip version 8.1.1 since an pip upgrade destroyed oh so much.

Read here in the issues about issue #22 etc, but no solution is working.

pip install pluginmgr==0.4.0
pip install vodka==2.2.3

That gave me same error as many others:

vaping start
Traceback (most recent call last):
File "/usr/local/bin/vaping", line 7, in 
from vaping.cli import cli
File "/usr/local/lib/python2.7/dist-packages/vaping/init.py", line 5, in 
from pluginmgr.config import ConfigPluginManager
ImportError: No module named pluginmgr.config

pip freeze
certifi==2018.4.16
chardet==3.0.4
click==6.7
docutils==0.14
future==0.16.0
gevent==1.3.5
greenlet==0.4.14
idna==2.7
lockfile==0.12.2
munge==0.6.0
pid==2.2.0
pluginmgr==0.4.0
python-daemon==2.1.2
PyYAML==3.13
requests==2.19.1
twentyc.tmpl==0.2.0
urllib3==1.23
vaping==0.6.1
vodka==2.2.3
whichcraft==0.4.1

Then tried pip install vaping==0.4.0

vaping start
Traceback (most recent call last):
  File "/home/jberg/.local/bin/vaping", line 11, in <module>
    sys.exit(cli())
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jberg/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/jberg/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jberg/.local/lib/python2.7/site-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/home/jberg/.local/lib/python2.7/site-packages/vaping/daemon.py", line 36, in __init__
    raise ValueError("no config specified, please use specify a home directory")
ValueError: no config specified, please use specify a home directory

How to install this properly and then the documentation *needs* an update. I prefer to run it on a ubuntu server or debian based system but if it works on any other distro I can try that also.

Thanks for your efforts, I'm looking forward to test Vaping the first time!

Br/Joel

**Comment by jorel83** [comment]
Sorry guys, this project seems to be awesome, but no instruction I find makes it possible to run on Debian based os, so what OS are you recommending? 

I'm a network engineer at a metro network and we currently use the not so great PingPlotter for troubleshooting stuff, however I would love to replace that with a better web frontend based open source so naturally planned on Smokeping but thats actually not a good replacement, but Vaping seems like it can be an suitable project.

I hope to find a way to actually make this work.

**Comment by vegu** [comment]
Where is your vaping config file located?

Have you looked at http://vaping.readthedocs.io/en/latest/quickstart/ ?

**Comment by grizz** [comment]
@jorel83 have you had a chance to try the quickstart yet? Most people use it on Ubuntu and it should work out of the box, #22 was from something else entirely

**Comment by vegu** [comment]
closing for inactivity - can reopen if a response is provided and help is still needed
