### ISSUE TITLE
internet uptime - tabular overview

### ISSUE THREAD

**Issue by kostadinnm** [20c/vaping#46]
Hello.
I'd like to trace the uptime of my Internet connection(broadband/pppoe accessed through an openwrt-flashed router). I managed to run vaping(the standalone example: `vaping start --home=examples/standalone_dns/ --debug`) on a fedora vm(level3 and opendns don't have values, but that's how fping is responding in my setup):
![2018-09-10 21_01_13](https://user-images.githubusercontent.com/18436405/45315881-3107e180-b53e-11e8-9674-3cc08fcd1d3f.jpg)
I plan to run this on a spare low-powered laptop(hooked to the router) for a while and I'd like to export the graph in some tabular way, so that I could show it to my ISP as they are doing some network rebuild(copper->fiber-optic) and the drops(sometimes overnight) are teasing me to hell. Some _**percentage total**_ column will be a pleasant addition, but unfortunately I have never worked with anything being utilized by vaping(graphsrv, vodka, graphite, mtr, zeromq, rrd, etc), which lead me to create this issue.

I know it won't be a perfect proof, but until I bring up a secondary internet access, I need my router running. The AC power at my place has definitely far less drops(I check the router uptime) than my internet connection. I went for all this, because I don't have many other options as the infrastructure of the other providers is similarly-prone to drops or outdated(adsl). As a fail-safe, I plan getting a 4g lte connection, but I hope for getting the stability back by my current ISP.

Any help appreciated!

Cheers,
Kostadin

**Comment by kostadinnm** [comment]
I have some progress - already outputting wsp files, though I'm unable to find a way to visualize them. Setting up a web service would be an overkill for my purposes.

**Comment by kostadinnm** [comment]
Ok, one last thing I am unable to do - when the connection is down(did it yesterday for 5 mins, I'm cutting it today artificially through my routerr), the vaping daemon fails to execute fping with this: 
> TypeError: update() argument after ** must be a mapping, not NoneType

In effect, the tracing loop gets cut. I tried setting a period of 3 seconds(3000ms) for the fping plugin, but it seems not to be enough. Is there a way to instruct it to write 0 to rrd-db and just continue with the next attempt from the schedule?!

**Comment by vegu** [comment]
Hi @kostadinnm - interesting progress on this

Can you paste the complete traceback of the error - but it's likely a bug in the vaping fping plugin where it should be more graceful.

**Comment by kostadinnm** [comment]
Here you are:
> Traceback (most recent call last):
>   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
>   File "/home/myuser/.local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 152, in _run
>     self._emit.emit(msg)
>   File "/home/myuser/.local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 269, in emit
>     filename = self.format_filename(message, row)
>   File "/home/myuser/.local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 257, in format_filename
>     return self.filename.format(**self.filename_formatters(data, row))
>   File "/home/myuser/.local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 246, in filename_formatters
>     r.update(**row)
> TypeError: update() argument after ** must be a mapping, not NoneType
> 2018-09-18T14:02:34Z <FPing "latency" at 0x7f9cf981ecb0: _run> failed with TypeError
> 

The thing is vaping is expecting answer from fping in the format: 

> ip: latency1 latency2 ...<newline> ip2: latency1 latency2 ....

But when there's no reply, fping starts with something like this: 

> ICMP Network Unreachable from <my_router_ip> for ICMP Echo sent to <dns/public gateway/google ip>

I need to track access to nodes outside my router, so even if I remove my router's ip from the config, fping starts with the icmp-not-reachable thing, thus the continuous tracing breaks.

Cheers,
Kostadin

**Comment by kostadinnm** [comment]
Well, I started to realize that those messages are kind of default and I cannot blame neither fping and maybe not even vaping itself. I read somewhere that they are returned only for important/known hosts, which may be the case(remember - I don't have a secondary connection to fetch a public ip I hadn't pinged before, so that it's not cached). If I point to a non-existing ip on my network, I don't get those messages.
The good news is I found a workaround, which would affect only the linux-box I am using. Following this: [Disable ICMP Unreachable replies](https://serverfault.com/questions/522709/disable-icmp-unreachable-replies), I disable the unreachable replies but for the input:
`iptables -I INPUT -p icmp --icmp-type destination-unreachable -j DROP`
In effect, I get the non-values(in terms of rrd) and I'll try it tomorrow to see how vaping reacts on an artificial connection drop.

Cheers,
Kostadin

**Comment by grizz** [comment]
@kostadinnm thanks for all the info. You can skip hops with the `fping_mtr` plugin, which might be more helpful.

Could you send me a full dump with fping version (via email is fine), we'd like to handle those ICMP messages correctly either way.

Cheers

**Comment by kostadinnm** [comment]
My hack with the iptables doesn't work. Attached is the full output that I get after I disconnect my internet connection from the router(I cleaned iptables' settings with `iptables -F`-command beforehand).
[error.txt](https://github.com/20c/vaping/files/2428052/error.txt)
