### ISSUE TITLE
Will not run at all - Red Hat 7.5

### ISSUE THREAD

**Issue by gmosley96** [20c/vaping#47]
This is what I did:
yum update
yum install python-devel.x86_64
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py (Python 2.7.5 on the system)
python get-pip.py
pip install vaping (installed version 1.0.0)
pip install -U vodka
pip install -U graphsrv

Installation didn't seem to create any directory structure or set any environment variables.
I created .vaping under /root and copied the example config file examples/standalone_dns/config.yml to /root/.vaping/config.yml

I type 'vaping start --home=/root/.vaping' and get:

missing fping, install it or set `command` in the fping config
Traceback (most recent call last):
  File "/usr/bin/vaping", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vaping/cli.py", line 58, in start
    daemon = mk_daemon(ctx)
  File "/usr/lib/python2.7/site-packages/vaping/cli.py", line 33, in mk_daemon
    return vaping.daemon.Vaping(ctx.config)
  File "/usr/lib/python2.7/site-packages/vaping/daemon.py", line 80, in __init__
    plugin.instantiate(self.config['plugins'], self.plugin_context)
  File "/usr/lib/python2.7/site-packages/pluginmgr/config.py", line 114, in instantiate
    self.new_plugin(plugin_config, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pluginmgr/config.py", line 64, in new_plugin
    obj = self._ctor(typ, config, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pluginmgr/config.py", line 45, in _ctor
    return self.get_plugin_class(typ)(config, *args, **kwargs)
  File "/root/.vaping/plugins/fping.py", line 34, in __init__
    raise RuntimeError("fping command not found")
RuntimeError: fping command not found

**Comment by 20c-ed** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/20c/vaping/issues/45 (Ubuntu - Running fail, how to deal with Vaping?), https://github.com/20c/vaping/issues/22 (Run issue on Ubuntu 16.04), https://github.com/20c/vaping/issues/4 (vaping stop doesn't work if running start --debug), and https://github.com/20c/vaping/issues/12 (Frequent crashes).

**Comment by gmosley96** [comment]
I wasn't able to "yum install fping" but I was able to d/l it and install it and that did solve THAT problem.

Now I get this:
vaping start --home=/root/.vaping --debug
pluginmgr ctor: self._instance={} self._class={} config.py:37
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins, ['/usr/lib/python2.7/site-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.abc, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match abc __init__.py:59
pluginmgr checking /root/.vaping/plugins/abc.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/abc.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.copy, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match copy __init__.py:59
pluginmgr checking /root/.vaping/plugins/copy.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/copy.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.datetime, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match datetime __init__.py:59
pluginmgr checking /root/.vaping/plugins/datetime.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/datetime.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.logging, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match logging __init__.py:59
pluginmgr checking /root/.vaping/plugins/logging.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/logging.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.munge, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match munge __init__.py:59
pluginmgr checking /root/.vaping/plugins/munge.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/munge.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.os, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match os __init__.py:59
pluginmgr checking /root/.vaping/plugins/os.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/os.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.future, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match future __init__.py:59
pluginmgr checking /root/.vaping/plugins/future.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/future.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.vaping, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb288> __init__.py:53
pluginmgr hook.match vaping __init__.py:59
pluginmgr checking /root/.vaping/plugins/vaping.py __init__.py:66
pluginmgr checking /root/.vaping/plugins/vaping.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.fping, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb198> __init__.py:53
pluginmgr hook.match fping __init__.py:59
pluginmgr checking /root/.vaping/plugins/fping.py __init__.py:66
pluginmgr hook.load(vaping.plugins.fping) __init__.py:71
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb198> __init__.py:90
pluginmgr checking /root/.vaping/plugins/fping.py __init__.py:66
pluginmgr hook.found(/root/.vaping/plugins/fping.py) __init__.py:99
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.util, ['/usr/lib/python2.7/site-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.shutil, ['/usr/lib/python2.7/site-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.whichcraft, ['/usr/lib/python2.7/site-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(whichcraft, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.loaded(vaping.plugins.fping) - <module 'fping' from '/root/.vaping/plugins/fping.pyc'> __init__.py:110
pluginmgr ctor: self._instance={'std_fping': <FPing "std_fping" at 0x7f776c290cb0: _run>} self._class={'fping': <class 'fping.FPing'>} config.py:37
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.vodka, ['/usr/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb198> __init__.py:53
pluginmgr hook.match vodka __init__.py:59
pluginmgr checking /root/.vaping/plugins/vodka.py __init__.py:66
pluginmgr hook.load(vaping.plugins.vodka) __init__.py:71
pluginmgr match <_sre.SRE_Match object at 0x7f776adbb198> __init__.py:90
pluginmgr checking /root/.vaping/plugins/vodka.py __init__.py:66
pluginmgr hook.found(/root/.vaping/plugins/vodka.py) __init__.py:99
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(graphsrv, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(graphsrv.group, ['/usr/lib/python2.7/site-packages/graphsrv']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(graphsrv.vodka, ['/usr/lib/python2.7/site-packages/graphsrv']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.loaded(vaping.plugins.vodka) - <module 'vodka' from '/root/.vaping/plugins/vodka.pyc'> __init__.py:110
PidFile <pid.PidFile object at 0x7f776bce3e18> entering setup __init__.py:71
PidFile <pid.PidFile object at 0x7f776bce3e18> create pidfile: /root/.vaping/vaping.pid __init__.py:161
PidFile <pid.PidFile object at 0x7f776bce3e18> check pidfile: /root/.vaping/vaping.pid __init__.py:148
pluginmgr ctor: self._instance={'vodka': <VodkaPlugin "vodka" at 0x7f776c290ec0: _run>, 'std_fping': <FPing "std_fping" at 0x7f776c290cb0: _run>} self._class={'vodka': <class 'vodka.VodkaPlugin'>, 'fping': <class 'fping.FPing'>} config.py:37
PidFile <pid.PidFile object at 0x7f776bce3e18> closing pidfile: /root/.vaping/vaping.pid __init__.py:188
Traceback (most recent call last):
  File "/usr/bin/vaping", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vaping/cli.py", line 61, in start
    daemon.run()
  File "/usr/lib/python2.7/site-packages/vaping/daemon.py", line 173, in run
    return self._main()
  File "/usr/lib/python2.7/site-packages/vaping/daemon.py", line 138, in _main
    probe._emit.start()
  File "/root/.vaping/plugins/vodka.py", line 60, in start
    vodka.run(self.config, self.vaping.config)
AttributeError: 'module' object has no attribute 'run'
PidFile <pid.PidFile object at 0x7f776bce3e18> closing pidfile: /root/.vaping/vaping.pid __init__.py:188
[root@svl-vaping1 .vaping]#

**Comment by vegu** [comment]
@gmosley96 can you paste the output of `pip freeze` please

**Comment by vegu** [comment]
closing for inactivity, can reopen in case of response - might be env issue, might be config issue
