### ISSUE TITLE
Fping error

### ISSUE THREAD

**Issue by marcorezzo** [20c/vaping#48]
Hello,

I am new to the Vaping / Smokeping system. So I tried installing and configuring Vaping the same way as the example installation. Don't worry I will adapt the configuration afterwards to my envirement.

So i get these errors when i try to execute this command: vaping start --home=examples/standalone_dns/ --debug

>
pluginmgr hook.match fping __init__.py:59
pluginmgr checking /home/pi/analyse/plugins/fping.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.util, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.shutil, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.whichcraft, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(whichcraft, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
vaping.plugins.fping missing fping, install it or set `command` in the fping config fping.py:33
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vaping/cli.py", line 58, in start
    daemon = mk_daemon(ctx)
  File "/usr/local/lib/python2.7/dist-packages/vaping/cli.py", line 33, in mk_daemon
    return vaping.daemon.Vaping(ctx.config)
  File "/usr/local/lib/python2.7/dist-packages/vaping/daemon.py", line 80, in __init__
    plugin.instantiate(self.config['plugins'], self.plugin_context)
  File "/usr/local/lib/python2.7/dist-packages/pluginmgr/config.py", line 114, in instantiate
    self.new_plugin(plugin_config, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluginmgr/config.py", line 64, in new_plugin
    obj = self._ctor(typ, config, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluginmgr/config.py", line 45, in _ctor
    return self.get_plugin_class(typ)(config, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/fping.py", line 34, in __init__
    raise RuntimeError("fping command not found")
RuntimeError: fping command not found
>

**Comment by vegu** [comment]
hello @marcorezzo 

looks like fping is missing from your system - see https://vaping.readthedocs.io/en/latest/quickstart/#install-vaping towards the bottom

**Comment by marcorezzo** [comment]
Hey @vegu
Thank you for helping out. I'm sorry for missing the last line. I installed fping and it works wonderfull.
