### ISSUE TITLE
Vaping crashes when given an IP that is unreachable

### ISSUE THREAD

**Issue by rgowrishankar** [20c/vaping#62]
Using the whisper example config file and changing one of the IPs to a random IP that is unreachable and get the following trace:
```
root@vsi-2:~# vaping start --home /root/whisper/ --verbose --debug
pluginmgr hook.compile(vaping.plugins) __init__.py:24
pluginmgr ctor: self._instance={} self._class={} config.py:37
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.abc, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match abc __init__.py:59
pluginmgr checking /root/whisper/plugins/abc.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.copy, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match copy __init__.py:59
pluginmgr checking /root/whisper/plugins/copy.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.datetime, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match datetime __init__.py:59
pluginmgr checking /root/whisper/plugins/datetime.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.logging, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match logging __init__.py:59
pluginmgr checking /root/whisper/plugins/logging.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.munge, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match munge __init__.py:59
pluginmgr checking /root/whisper/plugins/munge.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.os, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match os __init__.py:59
pluginmgr checking /root/whisper/plugins/os.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.future, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match future __init__.py:59
pluginmgr checking /root/whisper/plugins/future.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.vaping, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c947b0> __init__.py:53
pluginmgr hook.match vaping __init__.py:59
pluginmgr checking /root/whisper/plugins/vaping.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.fping, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb9c94a80> __init__.py:53
pluginmgr hook.match fping __init__.py:59
pluginmgr checking /root/whisper/plugins/fping.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.util, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.shutil, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.whichcraft, ['/usr/local/lib/python2.7/dist-packages/vaping']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(whichcraft, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr ctor: self._instance={'std_fping': <FPing "std_fping" at 0x7f5bba990788: _run>} self._class={'fping': <class 'vaping.plugins.fping.FPing'>} config.py:37
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(vaping.plugins.whisper, ['/usr/local/lib/python2.7/dist-packages/vaping/plugins']) loader=0 __init__.py:44
pluginmgr match <_sre.SRE_Match object at 0x7f5bb93e7030> __init__.py:53
pluginmgr hook.match whisper __init__.py:59
pluginmgr checking /root/whisper/plugins/whisper.py __init__.py:66
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(whisper, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.os, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.sys, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes._ctypes, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(_ctypes, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.struct, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.ctypes, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes._endian, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.util, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.subprocess, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.re, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.tempfile, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(ctypes.errno, ['/usr/lib/python2.7/ctypes']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(fadvise, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
PidFile <pid.PidFile object at 0x7f5bba73cbd0> entering setup __init__.py:77
PidFile <pid.PidFile object at 0x7f5bba73cbd0> create pidfile: /root/whisper/vaping.pid __init__.py:170
PidFile <pid.PidFile object at 0x7f5bba73cbd0> check pidfile: /root/whisper/vaping.pid __init__.py:157
pluginmgr ctor: self._instance={'whisper_avg': <WhisperPlugin "whisper_avg" at 0x7f5bba990998: _run>, 'std_fping': <FPing "std_fping" at 0x7f5bba990788: _run>} self._class={'whisper': <class 'vaping.plugins.whisper.WhisperPlugin'>, 'fping': <class 'vaping.plugins.fping.FPing'>} config.py:37
vaping.plugins.fping popen fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 169.61.160.200 __init__.py:67
root 8.8.8.8        : 1.93 1.81 1.87 1.93 1.99 1.81 1.89 1.97 1.87 1.88
 fping.py:68
root 4.2.2.1        : 1.93 1.88 1.85 1.83 1.75 1.91 1.68 1.81 1.80 1.84
 fping.py:68
root 169.61.160.200 : - - - - - - - - - -
 fping.py:68
vaping.plugins.fping queue emission to whisper_avg (0) __init__.py:144
vaping.plugins.fping emit to whisper_avg __init__.py:141
vaping.plugins.whisper storing time:1570722401, avg:1.89500 in latency-8.8.8.8-avg.wsp __init__.py:423
vaping.plugins.whisper storing time:1570722401, avg:1.82800 in latency-4.2.2.1-avg.wsp __init__.py:423
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(gevent.platform, ['/usr/local/lib/python2.7/dist-packages/gevent']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(gevent.ctypes, ['/usr/local/lib/python2.7/dist-packages/gevent']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(gevent.__pypy__, ['/usr/local/lib/python2.7/dist-packages/gevent']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(__pypy__, None) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(gevent.cPickle, ['/usr/local/lib/python2.7/dist-packages/gevent']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
pluginmgr hook.namespace vaping.plugins __init__.py:43
pluginmgr hook.find(gevent.copy_reg, ['/usr/local/lib/python2.7/dist-packages/gevent']) loader=0 __init__.py:44
pluginmgr match None __init__.py:53
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/__init__.py", line 185, in _run
    self.emit_all()
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/__init__.py", line 162, in emit_all
    self.send_emission()
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/__init__.py", line 154, in send_emission
    emit()
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/__init__.py", line 142, in emit
    emitter.emit(msg)
  File "/usr/local/lib/python2.7/dist-packages/vaping/plugins/__init__.py", line 423, in emit
    message.get("ts"), self.field, row.get(self.field), filename))
TypeError: float argument required, not NoneType
2019-10-10T15:46:44Z <FPing "latency" at 0x7f5bba990aa0: _run> failed with TypeError

PidFile <pid.PidFile object at 0x7f5bba73cbd0> closing pidfile: /root/whisper/vaping.pid __init__.py:197
vaping.daemon stopping whisper_avg daemon.py:184
vaping.daemon stopping latency daemon.py:184
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vaping/cli.py", line 61, in start
    daemon.run()
  File "/usr/local/lib/python2.7/dist-packages/vaping/daemon.py", line 174, in run
    return self._main()
  File "/usr/local/lib/python2.7/dist-packages/vaping/daemon.py", line 145, in _main
    vaping.io.joinall(self.joins)
  File "src/gevent/greenlet.py", line 899, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 909, in gevent._greenlet.joinall
  File "src/gevent/_hub_primitives.py", line 217, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 254, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 152, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_hub_primitives.py", line 143, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_waiter.py", line 192, in gevent.__waiter.MultipleWaiter.get
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7f5bba99d890 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7f5bbe0ad740>
	Handles:
[]
PidFile <pid.PidFile object at 0x7f5bba73cbd0> closing pidfile: /root/whisper/vaping.pid __init__.py:197
```

**Comment by vegu** [comment]
@rgowrishankar sorry meant to look at this last week, but never found the time - saw your pull request for a fix for this as well, will poke this tomorrow - thanks!

**Comment by rgowrishankar** [comment]
@vegu sure, no issues.

**Comment by rgowrishankar** [comment]
https://github.com/20c/vaping/pull/63 -- potential fix.
