### ISSUE TITLE
TypeError: "value" must be an int or a float, not a NoneType

### ISSUE THREAD

**Issue by bhuddah** [20c/vaping#78]
### Version

vaping, version 1.2.0

### Traceback
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/__init__.py", line 234, in _run
    self.emit_all()
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/__init__.py", line 211, in emit_all
    self.send_emission()
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/__init__.py", line 203, in send_emission
    emit()
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/__init__.py", line 191, in emit
    emitter.emit(msg)
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/__init__.py", line 530, in emit
    self.update(filename, message.get("ts"), row.get(self.field))
  File "/usr/local/lib/python3.7/dist-packages/vaping/plugins/graphite.py", line 47, in update
    graphyte.send('{}'.format(filename), value, time)
  File "/usr/local/lib/python3.7/dist-packages/graphyte.py", line 203, in send
    default_sender.send(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/graphyte.py", line 103, in send
    message = self.build_message(metric, value, timestamp, tags)
  File "/usr/local/lib/python3.7/dist-packages/graphyte.py", line 77, in build_message
    type(value).__name__))
TypeError: "value" must be an int or a float, not a NoneType
2019-12-28T02:11:07Z <FPing "fping" at 0x756e58a0: _run> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/vaping/cli.py", line 75, in start
    daemon.run()
  File "/usr/local/lib/python3.7/dist-packages/vaping/daemon.py", line 179, in run
    return self._main()
  File "/usr/local/lib/python3.7/dist-packages/vaping/daemon.py", line 150, in _main
    vaping.io.joinall(self.joins)
  File "src/gevent/greenlet.py", line 899, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 909, in gevent._greenlet.joinall
  File "src/gevent/_hub_primitives.py", line 217, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 254, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 152, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_hub_primitives.py", line 143, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_waiter.py", line 192, in gevent.__waiter.MultipleWaiter.get
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
        Hub: <Hub '' at 0x75511450 epoll default pending=0 ref=0 fileno=3 thread_ident=0x76f19ad0>
        Handles:
[]
```

### Config

```
probes:
  - name: fping
    type: std_fping
    output:
      - graphite_avg
      - graphite_min
      - graphite_max
      - graphite_loss


    groups:
      - name: public_dns
        hosts:
          - host: ***
            name: ***
          - host: ***
            name: ***
          - host: ***
            name: ***
          - host: ***
            name: ***

plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 10s
    output:
      - graphite_avg
      - graphite_min
      - graphite_max
      - graphite_loss

  - name: graphite_avg
    type: graphite

    # will create one file per host
    filename: "{source}-{host}-{field}"
    graphite_host: "127.0.0.1"
    protocol: "http"
    prefix: "vaping"
    # specified which field to retrieve the value from
    field: avg

  - name: graphite_min
    type: graphite

    # will create one file per host
    filename: "{source}-{host}-{field}"
    graphite_host: "127.0.0.1"
    protocol: "http"
    prefix: "vaping"
    # specified which field to retrieve the value from
    field: min


  - name: graphite_max
    type: graphite

    # will create one file per host
    filename: "{source}-{host}-{field}"
    graphite_host: "127.0.0.1"
    protocol: "http"
    prefix: "vaping"
    # specified which field to retrieve the value from
    field: max


  - name: graphite_loss
    type: graphite

    # will create one file per host
    filename: "{source}-{host}-{field}"
    graphite_host: "127.0.0.1"
    protocol: "http"
    prefix: "vaping"
    # specified which field to retrieve the value from
    field: loss
```

**Comment by bhuddah** [comment]
looks like duplicate of #62

**Comment by vegu** [comment]
@bhuddah thanks for the bug report

Agree that it looks very similar to #62, probably just needs the same fix applied to the graphite plugin that was applied in 083edf01df902470a5d39c7edacb3136222eb24d to the whisper and rrd plugins
