### ISSUE TITLE
default config dir

### ISSUE THREAD

**Issue by justinc1** [20c/vaping#8]
Immediately after pip install vaping:
```
(vaping)justin_cinkelj@jcdell ~ $ vaping start
Traceback (most recent call last):
  File "/home/justin_cinkelj/.virtualenvs/vaping/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.2.0', 'console_scripts', 'vaping')()
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/daemon.py", line 48, in __init__
    self.home_dir = os.path.abspath(self.config.meta['config_dir'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Could a default config file/dir be auto-created?

Also, error message like "Specify a valid VAPING_HOME, for example $0 --home ./.vaping" would be nice.

**Comment by justinc1** [comment]
```
mkdir ~/.vaping

(vaping)justin_cinkelj@jcdell ~ $ vaping --debug --home ~/.vaping start
Traceback (most recent call last):
  File "/home/justin_cinkelj/.virtualenvs/vaping/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.2.0', 'console_scripts', 'vaping')()
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/cli.py", line 40, in cli
    update_context(ctx, kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/cli.py", line 21, in update_context
    ctx.update_options(kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/munge/click.py", line 70, in update_options
    self.config = self.config_class(read=self.home)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/munge/config.py", line 59, in __init__
    self.read(kwargs['read'])
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/munge/config.py", line 138, in read
    raise IOError("config file not found in %s" % (conf_path,))
IOError: config file not found in /home/justin_cinkelj/.vaping
```

So I create the official config file:
```
(vaping)justin_cinkelj@jcdell ~ $ cat ~/.vaping/config.yml 
vaping:
  pidfile: vaping.pid
  plugin_path: []


probes:

plugins:
(vaping)justin_cinkelj@jcdell ~ $ 
(vaping)justin_cinkelj@jcdell ~ $ vaping --debug --home ~/.vaping start
pluginmgr hook.compile(vaping.plugins) __init__.py:25
Traceback (most recent call last):
  File "/home/justin_cinkelj/.virtualenvs/vaping/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.2.0', 'console_scripts', 'vaping')()
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/daemon.py", line 53, in __init__
    plugin.instantiate(config['plugins'], self.plugin_context)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/pluginmgr/__init__.py", line 272, in instantiate
    for plugin_config in config:
TypeError: 'NoneType' object is not iterable
(vaping)justin_cinkelj@jcdell ~ $ 
```

Should I add one plugin from .virtualenvs/vaping/lib/python2.7/site-packages/vaping/plugins?

**Comment by justinc1** [comment]
I was not able to write valid config from zero :/

But even after usgin example from wget https://raw.githubusercontent.com/20c/vaping/master/examples/distributed_dns/vodka/config.yml , I still get:
```
(vaping)justin_cinkelj@jcdell .vaping $ vaping --debug --home ~/.vaping start
pluginmgr hook.compile(vaping.plugins) __init__.py:25
pluginmgr ctor: self._instance {} __init__.py:200
pluginmgr ctor: self._class {} __init__.py:201
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping']) loader=0 __init__.py:45
pluginmgr match None __init__.py:54
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins.abc, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:45
pluginmgr match <_sre.SRE_Match object at 0x7f4331be6210> __init__.py:54
pluginmgr hook.match abc __init__.py:60
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/abc.py __init__.py:67
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/abc.py __init__.py:67
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins.datetime, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:45
pluginmgr match <_sre.SRE_Match object at 0x7f4331be6210> __init__.py:54
pluginmgr hook.match datetime __init__.py:60
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/datetime.py __init__.py:67
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/datetime.py __init__.py:67
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins.logging, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:45
pluginmgr match <_sre.SRE_Match object at 0x7f4331be6210> __init__.py:54
pluginmgr hook.match logging __init__.py:60
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/logging.py __init__.py:67
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/logging.py __init__.py:67
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins.vaping, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:45
pluginmgr match <_sre.SRE_Match object at 0x7f4331be6210> __init__.py:54
pluginmgr hook.match vaping __init__.py:60
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/vaping.py __init__.py:67
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/vaping.py __init__.py:67
pluginmgr hook.namespace vaping.plugins __init__.py:44
pluginmgr hook.find(vaping.plugins.zeromq_probe, ['/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/plugins']) loader=0 __init__.py:45
pluginmgr match <_sre.SRE_Match object at 0x7f4331be6be8> __init__.py:54
pluginmgr hook.match zeromq_probe __init__.py:60
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/zeromq_probe.py __init__.py:67
pluginmgr checking /home/justin_cinkelj/.vaping/plugins/zeromq_probe.py __init__.py:67
pluginmgr ImportError No module named zeromq_probe __init__.py:194
Traceback (most recent call last):
  File "/home/justin_cinkelj/.virtualenvs/vaping/bin/vaping", line 9, in <module>
    load_entry_point('vaping==0.2.0', 'console_scripts', 'vaping')()
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/cli.py", line 54, in start
    daemon = vaping.daemon.Vaping(ctx.config)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/vaping/daemon.py", line 53, in __init__
    plugin.instantiate(config['plugins'], self.plugin_context)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/pluginmgr/__init__.py", line 273, in instantiate
    self.new_plugin(plugin_config, *args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/pluginmgr/__init__.py", line 230, in new_plugin
    obj = self._ctor(typ, config, *args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/pluginmgr/__init__.py", line 209, in _ctor
    return self.get_plugin_class(typ)(config, *args, **kwargs)
  File "/home/justin_cinkelj/.virtualenvs/vaping/local/lib/python2.7/site-packages/pluginmgr/__init__.py", line 196, in get_plugin_class
    raise ValueError("unknown plugin '%s'" % typ)
ValueError: unknown plugin 'zeromq_probe'
(vaping)justin_cinkelj@jcdell .vaping $ 

```

**Comment by justinc1** [comment]
Hm hm hm...
I should be using python3 ...
But that could/should be checked too.

**Comment by laapsaap** [comment]
Please state it in the README.md stating that vaping doesnt work with python2 and save us mortals some time/headache. Rather deal with perl smokeping than python3

**Comment by grizz** [comment]
@laapsaap it works out of the box with python2, it's the python3 code that wasn't released to pypi, please open a ticket with what problem you're having

**Comment by grizz** [comment]
@justinc1 Sorry for the delay, missed these emails. Your second problem is `plugins` and `probes` should be set to `[]` -- I've added tests and better error messages on HEAD, will release to pypi after testing finishes
